/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:c9754747-82b5-45d5-8f12-9ddaa34db4b5",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_ywl2IdeCL",
    "aws_user_pools_web_client_id": "4jhjf35u45250tfbmrm1c7t8c0",
    "oauth": {
        "domain": "new-test2-dev.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dev.d28mji38lr86lo.amplifyapp.com/",
        "redirectSignOut": "https://dev.d28mji38lr86lo.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
